name: Update Labels

on:
  pull_request:
    branches: [main]
    types:
      [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  labels-test:
    name: Assigns and test labels reading conventional-commits
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Assign labels
        id: action-assign-labels
        uses: mauroalderete/action-assign-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'fix'
                nouns: ['FIX', 'Fix', 'fix', 'FIXED', 'Fixed', 'fixed']
                labels: ['bug']
              - type: 'feature'
                nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat']
                labels: ['enhancement']
              - type: 'breaking_change'
                nouns: ['BREAKING CHANGE', 'BREAKING', 'MAJOR']
                labels: ['BREAKING CHANGE']
              - type: 'dependencies'
                nouns: ['dependencies','dependencie','depends','depend','deps','dep']
                labels: ['dependencies','bug']
              - type: 'documentation'
                nouns: ['doc','docu','document','documentation']
                labels: ['documentation','bug']
              - type: 'build'
                nouns: ['build','rebuild']
                labels: ['build','bug']
              - type: 'config'
                nouns: ['config', 'conf', 'cofiguration', 'configure']
                labels: ['config','bug']
              - type: 'test'
                nouns: ['test','tests','testing']
                labels: ['test','bug']

      - name: Verify labels
        id: action-verify-labels
        uses: mauroalderete/action-verify-labels@v1
        with:
          none: question, wontfix, invalid, help wanted, good first issue, duplicate
          some: BREAKING CHANGE, enhancement, bug, documentation, dependencies, build, config
          request-review: true
          request-review-header: '**:bookmark: verify-labels-action**'
          github-token: ${{ secrets.GITHUB_TOKEN }}
